### PR TITLE
Remove unsed trait

### PR DESCRIPTION
**Pull request by wangzhen11aaa**
Remove unsed trait.
Will we add this `Clone` trait without any cost？

### CODE REVIEW

**Comment by skyzh** [comment]
Indeed, `Copy` requires `Clone`, so this change indeed takes no effect :)

https://doc.rust-lang.org/src/core/marker.rs.html#383-385

Adding `Clone` trait won't add significant cost, from my perspective.

**Comment by wangzhen11aaa** [comment]
> Indeed, `Copy` requires `Clone`, so this change indeed takes no effect :)
> 
> https://doc.rust-lang.org/src/core/marker.rs.html#383-385
> 
> Adding `Clone` trait won't add significant cost, from my perspective.

Ok, I'll see. I think `Clone` coupled with `Copy` is something like thought inertia. :D

**Comment by wangzhen11aaa** [comment]
> > Indeed, `Copy` requires `Clone`, so this change indeed takes no effect :)
> > https://doc.rust-lang.org/src/core/marker.rs.html#383-385
> > Adding `Clone` trait won't add significant cost, from my perspective.
> 
> Ok, I'll see. I think `Clone` coupled with `Copy` is something like thought inertia. :D

#[derive(Copy, Clone, Debug, PartialEq)]
What's more, for `Clone` is the supertrait of `Copy`, then It is a good inertia, maybe.

**Comment by skyzh** [comment]
Yes, I think I was impacted by the derive inertia. Sounds reasonable not to + Clone here.

**Comment by skyzh** [comment]
Oops, the commit title on main branch looks weird. I’ll do a force push tomorrow to fix it.

**Pull request merged**
